name: Compile Libpostal and Jpostal

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl autoconf automake libtool pkg-config

      - name: Build Libpostal
        run: |
          git clone https://github.com/openvenues/libpostal.git
          cd libpostal
          ./bootstrap.sh
          ./configure --datadir=/tmp/libpostal-data
          make
          sudo make install

      - name: Build Jpostal
        run: |
          git clone https://github.com/openvenues/jpostal.git
          cd jpostal
          ./gradlew assemble

      - name: Copy Jpostal and Libpostal Libraries
        run: |
          mkdir -p libs/jpostal
          mkdir -p libs/libpostal
          cp -r jpostal/build/libs/* libs/jpostal/
          cp /usr/local/lib/libpostal.so* libs/libpostal/
          cp -r /tmp/libpostal-data libs/libpostal/

      - name: Configure Git
        run: |
          git config --global user.name 'jonv11'
          git config --global user.email 'jonv11@users.noreply.github.com'

      - name: Debug Git Status
        run: |
          git status
          git config --list

      - name: Check PAT Authentication
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" https://api.github.com/user

      - name: Commit and Push Changes
        run: |
          git add libs/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Add compiled jpostal and libpostal libraries"
            git push https://${{ secrets.PAT_TOKEN }}@github.com/jonv11/test-gh-actions.git HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
